const examplePokemons = [
  {
    Row: 1,
    Name: 'Bulbasaur',
    PokedexNumber: 1,
    ImgName: 'bulbasaur.png',
    Generation: 1,
    EvolutionStage: 1,
    Evolved: 0,
    FamilyID: 1,
    CrossGen: 0,
    Type1: 'grass',
    Type2: 'poison',
    Weather1: 'Sunny/clear',
    Weather2: 'Cloudy',
    STAT_TOTAL: 326,
    ATK: 118,
    DEF: 118,
    STA: 90,
    Legendary: 0,
    Aquireable: 1,
    Spawns: 1,
    Regional: 0,
    Raidable: 0,
    Hatchable: 5,
    Shiny: 0,
    Nest: 0,
    New: 1,
    NotGettable: 0,
    FutureEvolve: 0,
    CP100_40: 981,
    CP100_39: 967
  },
  {
    Row: 2,
    Name: 'Ivysaur',
    PokedexNumber: 2,
    ImgName: 'ivysaur.png',
    Generation: 1,
    EvolutionStage: 2,
    Evolved: 1,
    FamilyID: 1,
    CrossGen: 0,
    Type1: 'grass',
    Type2: 'poison',
    Weather1: 'Sunny/clear',
    Weather2: 'Cloudy',
    STAT_TOTAL: 405,
    ATK: 151,
    DEF: 151,
    STA: 103,
    Legendary: 0,
    Aquireable: 1,
    Spawns: 1,
    Regional: 0,
    Raidable: 0,
    Hatchable: 5,
    Shiny: 0,
    Nest: 0,
    New: 0,
    NotGettable: 0,
    FutureEvolve: 1,
    CP100_40: 1552,
    CP100_39: 1532
  },
  {
    Row: 3,
    Name: 'Venusaur',
    PokedexNumber: 3,
    ImgName: 'venusaur.png',
    Generation: 1,
    EvolutionStage: 3,
    Evolved: 1,
    FamilyID: 1,
    CrossGen: 0,
    Type1: 'grass',
    Type2: 'poison',
    Weather1: 'Sunny/clear',
    Weather2: 'Cloudy',
    STAT_TOTAL: 525,
    ATK: 198,
    DEF: 198,
    STA: 129,
    Legendary: 0,
    Aquireable: 1,
    Spawns: 1,
    Regional: 0,
    Raidable: 0,
    Hatchable: 5,
    Shiny: 0,
    Nest: 0,
    New: 0,
    NotGettable: 0,
    FutureEvolve: 0,
    CP100_40: 2568,
    CP100_39: 2531
  }
];

module.exports = examplePokemons;
